[application]
# `build` & `serve` output path
out_dir = "dist"
# The static resource path
asset_dir = "public"

[web.app]
# HTML title tag content
title = "Brock Tomlinson"

# include `assets` in web platform
[web.resource]
base_path = "darkicewolf50.github.io"
# Additional CSS style files
style = []
# Additional JavaScript files
script = []

[web.resource.dev]
# Javascript code file
# serve: [dev-server] only
script = []
